/** RUTAS DE INSPECCIÓN V12 - Base central en Google Sheets */
const FOLDER='Rutas de Inspección';
const BOOK='Base Central - Rutas de Inspección';
const SHEETS={places:'Subestaciones',history:'Historial',users:'Usuarios'};
function doGet(e){try{const action=(e.parameter.action||'all');let data={ok:true};if(action==='all'){data.places=readSheet_(SHEETS.places);data.history=readSheet_(SHEETS.history);data.users=readSheet_(SHEETS.users);data.sheetUrl=getBook_().getUrl()}else if(action==='places')data.places=readSheet_(SHEETS.places);else if(action==='history')data.history=readSheet_(SHEETS.history);return out_(data,e.parameter.callback)}catch(err){return out_({ok:false,error:err.message},e.parameter.callback)}}
function doPost(e){const lock=LockService.getScriptLock();lock.waitLock(10000);try{const b=JSON.parse((e.postData&&e.postData.contents)||'{}');if(b.action==='place')upsert_(SHEETS.places,b.payload,'id');if(b.action==='history')upsert_(SHEETS.history,b.payload,'id');if(b.action==='user')upsert_(SHEETS.users,b.payload,'name');return ContentService.createTextOutput(JSON.stringify({ok:true})).setMimeType(ContentService.MimeType.JSON)}catch(err){return ContentService.createTextOutput(JSON.stringify({ok:false,error:err.message})).setMimeType(ContentService.MimeType.JSON)}finally{lock.releaseLock()}}
function getBook_(){const props=PropertiesService.getScriptProperties();const id=props.getProperty('BOOK_ID');if(id){try{return SpreadsheetApp.openById(id)}catch(e){}}const folders=DriveApp.getFoldersByName(FOLDER);const folder=folders.hasNext()?folders.next():DriveApp.createFolder(FOLDER);const ss=SpreadsheetApp.create(BOOK);DriveApp.getFileById(ss.getId()).moveTo(folder);props.setProperty('BOOK_ID',ss.getId());setup_(ss);return ss}
function setup_(ss){const defs={Subestaciones:['id','feeder','substation','address','lat','lon','updatedAt'],Historial:['id','date','user','feeder','substation','address','order','distance','duration','status','lat','lon'],Usuarios:['name','role','lastAccess']};Object.keys(defs).forEach((n,i)=>{let sh=i===0?ss.getSheets()[0]:ss.insertSheet();sh.setName(n);sh.getRange(1,1,1,defs[n].length).setValues([defs[n]]).setFontWeight('bold').setBackground('#dbeafe');sh.setFrozenRows(1)})}
function readSheet_(name){const sh=getBook_().getSheetByName(name);const v=sh.getDataRange().getValues();if(v.length<2)return[];const h=v[0];return v.slice(1).filter(r=>r.some(x=>x!=='' )).map(r=>{const o={};h.forEach((k,i)=>o[k]=r[i]);return o})}
function upsert_(name,obj,key){if(!obj)return;const sh=getBook_().getSheetByName(name);const v=sh.getDataRange().getValues();const h=v[0];const idx=h.indexOf(key);let row=-1;for(let i=1;i<v.length;i++)if(String(v[i][idx])===String(obj[key])){row=i+1;break}const vals=h.map(k=>obj[k]??'');if(row>0)sh.getRange(row,1,1,h.length).setValues([vals]);else sh.appendRow(vals)}
function out_(obj,cb){const json=JSON.stringify(obj);if(cb)return ContentService.createTextOutput(`${cb}(${json})`).setMimeType(ContentService.MimeType.JAVASCRIPT);return ContentService.createTextOutput(json).setMimeType(ContentService.MimeType.JSON)}
function initializeDatabase(){return getBook_().getUrl()}
